### ISSUE TITLE
Error while setting up sample-memory-relay on Windows

### ISSUE THREAD

**Issue by sagarrao** [Flipkart/aesop#46]
I have been following the instrutctions provided on this :

https://github.com/Flipkart/aesop/wiki/Relay-Examples

to setup a new memory-relay server. I have follwed the exact same instrutcion set but when I start my service using:

    java -cp "./target/sample-memory-relay-1.2.1-SNAPSHOT.jar:./target/lib/*" org
.trpr.platform.runtime.impl.bootstrap.BootstrapLauncher  ./src/main/resources/e
xternal/bootstrap.xml

I keep getting this exception in my logs:

16:09:34.185 [main] WARN  o.eclipse.jetty.webapp.WebAppContext - Failed startup
of context o.e.j.w.WebAppContext{/,null},file:\C:\aesop\samples\sample-memory-re
lay\target\lib\runtime-relay-1.2.1-SNAPSHOT.jar!\
java.io.FileNotFoundException: file:\C:\aesop\samples\sample-memory-relay\target
\lib\runtime-relay-1.2.1-SNAPSHOT.jar!\
        at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfigurati
on.java:495) ~[jetty-webapp-8.1.5.v20120716.jar:8.1.5.v20120716]
        at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfi
guration.java:64) ~[jetty-webapp-8.1.5.v20120716.jar:8.1.5.v20120716]
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.jav
a:438) ~[jetty-webapp-8.1.5.v20120716.jar:8.1.5.v20120716]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:474
) ~[jetty-webapp-8.1.5.v20120716.jar:8.1.5.v20120716]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:59) [jetty-util-8.1.5.v20120716.jar:8.1.5.v20120716]
        at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCol
lection.java:224) [jetty-server-8.1.5.v20120716.jar:8.1.5.v20120716]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(Con
textHandlerCollection.java:167) [jetty-server-8.1.5.v20120716.jar:8.1.5.v2012071
6]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:59) [jetty-util-8.1.5.v20120716.jar:8.1.5.v20120716]
        at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCol
lection.java:224) [jetty-server-8.1.5.v20120716.jar:8.1.5.v20120716]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:59) [jetty-util-8.1.5.v20120716.jar:8.1.5.v20120716]
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrappe
r.java:90) [jetty-server-8.1.5.v20120716.jar:8.1.5.v20120716]
        at org.eclipse.jetty.server.Server.doStart(Server.java:272) [jetty-serve
r-8.1.5.v20120716.jar:8.1.5.v20120716]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:59) [jetty-util-8.1.5.v20120716.jar:8.1.5.v20120716]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.
0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.
0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:
1.8.0_45]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_45]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1638) [sp
ring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1579) [spring-
beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.initializeBean(AbstractAutowireCapableBeanFactory.java:1509) [spring-bea
ns-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521) [spring-beans-
3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBean(AbstractAutowireCapableBeanFactory.java:458) [spring-beans-3.
2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getOb
ject(AbstractBeanFactory.java:296) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE
]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistr
y.getSingleton(DefaultSingletonBeanRegistry.java:223) [spring-beans-3.2.5.RELEAS
E.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
an(AbstractBeanFactory.java:293) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
(AbstractBeanFactory.java:194) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.
preInstantiateSingletons(DefaultListableBeanFactory.java:628) [spring-beans-3.2.
5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finish
BeanFactoryInitialization(AbstractApplicationContext.java:932) [spring-context-3
.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refres
h(AbstractApplicationContext.java:479) [spring-context-3.2.5.RELEASE.jar:3.2.5.R
ELEASE]
        at org.springframework.context.support.ClassPathXmlApplicationContext.<i
nit>(ClassPathXmlApplicationContext.java:139) [spring-context-3.2.5.RELEASE.jar:
3.2.5.RELEASE]
        at org.springframework.context.support.ClassPathXmlApplicationContext.<i
nit>(ClassPathXmlApplicationContext.java:105) [spring-context-3.2.5.RELEASE.jar:
3.2.5.RELEASE]
        at com.flipkart.aesop.runtime.spring.RuntimeComponentContainer.init(Runt
imeComponentContainer.java:151) [runtime-1.2.1-SNAPSHOT.jar:na]
        at org.trpr.platform.runtime.impl.container.spring.SpringContainerImpl.i
nit(SpringContainerImpl.java:102) [runtime-core-1.3.1.jar:na]
        at org.trpr.platform.runtime.impl.bootstrap.spring.Bootstrap.start(Boots
trap.java:248) [runtime-core-1.3.1.jar:na]
        at org.trpr.platform.runtime.impl.bootstrap.spring.Bootstrap.init(Bootst
rap.java:135) [runtime-core-1.3.1.jar:na]
        at org.trpr.platform.runtime.impl.bootstrap.BootstrapLauncher.main(Boots

Even though my server logs say that the app has started, but when I hit localhost:9090, I get a 503.

Since I am using windows, I have been exceuting these commands on gitbash.

**Comment by aryaKetan** [comment]
Hi @sagarrao , none of us have tried this on a windows machine yet. Now, from the logs, it looks like there might be issues with finding out file-path / code-path. So, you may not be able to run samples directly, but might have to make changes in the config files to ensure that the correct path as per Windows machine format requirements is being pointed to in the configs.

**Comment by sagarrao** [comment]
@aryaKetan  That's what even I was wondering. One of the things I was looking at is :

 <bean id="bootstrapInfo" class="org.trpr.platform.runtime.spi.bootstrap.BootstrapInfo">
        <property name="projectsRoot" value="$RUNTIME_CONFIG_PATH/../../" />

This is what is being parsed I believe through the runtime jar. Any more configs that I should be looking at?

**Comment by aryaKetan** [comment]
Please check all *xml files for any path related config.

**Comment by aryaKetan** [comment]
Hi, can u check if the file C:\aesop\samples\sample-memory-relay\target
\lib\runtime-relay-1.2.1-SNAPSHOT.jar is present in ur local.

**Comment by regunathb** [comment]
Closing this due to inactivity from reporter of issue.
