### ISSUE TITLE
IllegalArgumentException with mysql-relayer 

### ISSUE THREAD

**Issue by shubhamf** [Flipkart/aesop#61]
Hi I am getting this exception 

`18:58:48.220 [binlog-parser-1] ERROR c.g.c.o.OpenReplicator$ORBinlogParserListener.onException 103 c.g.code.or.common.util.QueryUtil - Exception occured in binlogParser
java.lang.IllegalArgumentException: invalid value: 16777215
	at com.google.code.or.common.glossary.column.Int24Column.valueOf(Int24Column.java:70) ~[open-replicator-1.0.8.jar:na]
	at com.google.code.or.binlog.impl.parser.AbstractRowEventParser.parseRow(AbstractRowEventParser.java:152) ~[open-replicator-1.0.8.jar:na]
	at com.google.code.or.binlog.impl.parser.WriteRowsEventV2Parser.parseRows(WriteRowsEventV2Parser.java:75) ~[open-replicator-1.0.8.jar:na]
	at com.google.code.or.binlog.impl.parser.WriteRowsEventV2Parser.parse(WriteRowsEventV2Parser.java:64) ~[open-replicator-1.0.8.jar:na]
	at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.doParse(ReplicationBasedBinlogParser.java:147) ~[open-replicator-1.0.8.jar:na]
	at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:308) ~[open-replicator-1.0.8.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
18:58:48.221 [binlog-parser-1] INFO  c.g.c.o.OpenReplicator$ORBinlogParserListener.onException 104 c.g.code.or.common.util.QueryUtil - Retrying the prassing from : mysql-bin.000017:794805
`

Can anyone help me what this error is and how to solve this issue?

**Comment by shubhamf** [comment]
This is a bug in open-replicator which is fixed by zendesk. Can we move to this release.
`<groupId>com.zendesk</groupId>
 <artifactId>open-replicator</artifactId>
 <version>1.1.1</version>`

Steps to recreate error

Create a table with column of mediumint and insert value into it.

**Comment by shubhamf** [comment]
Fixed in pull request https://github.com/Flipkart/aesop/pull/62
